
spring:
  datasource:

    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASS_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2

cloudinary:
  cloud_name: ${CLOUD_NAME_CLOUDINARY}
  api_key: ${API_KEY_CLOUDINARY}
  api_secret: ${API_SECRET_CLOUDINARY}